# Spring Configurations
spring:
  cache:
    type: redis
    cache-names: studentdata
  application:
    name: redis-cache-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      minimumIdle: 5
      maximumPoolSize: 50
      connectionTimeout: 2000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: false
  redis:
    host: 
    port: 
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console

# Swagger endpoints
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    defaultModelsExpandDepth: -1
